FROM php:8.3-fpm

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        git unzip libpq-dev && \
    docker-php-ext-install pdo pdo_pgsql && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www